version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ticketsApp
      POSTGRES_DB: ticket_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: docker
      PORT: 5001
      DATABASE_URL: postgresql://postgres:ticketsApp@db:5432/ticket_app
      jwtSecret: ticket_app@2025
    ports:
      - "5001:5001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: